name: An치lise PowerBuilder (PBAnalyzer)

on:
#  pull_request:
#    branches:
#      - main
  push:
    branches:
      - main

jobs:
  analyze:
    name: Rodar PBAnalyzer
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do reposit칩rio
        uses: actions/checkout@v5

      - name: Configurar JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: maven

      - name: Compilar com Maven
        run: mvn -B clean package --file pom.xml

      - name: Executar PBAnalyzer
        run: java -jar target/pbanalyzer-1.0-SNAPSHOT.jar ./src > report.txt

      - name: Exibir relat칩rio
        run: cat relatorio.json

      - name: Falhar se houver problemas detectados
        run: |
          if grep -q "ERRO" report.txt; then
            echo "Erros encontrados na an치lise!"
            exit 1
          else
            echo "Nenhum erro encontrado."
          fi